services:
    _defaults:
        autoconfigure: true
    VTInnovations\Accessplus\Controller\AltTagsController:
        arguments:
            - '@contao.framework'
        tags: ['controller.service_arguments']
    
    VTInnovations\Accessplus\Backend\AccessbilityAnalysis:
        arguments:
            - '@http_client'
        tags: ['contao.backend_module']
